sudo: false
addons:
  jwt:
    secure: JMPPMkxcqYQQJTmXXj6VHAdNny+95vTWFzY6tV4wFMydTurAX5Rw4H2qotEQjcPHml/8ifB/x/9wjLYEuZ+ZTD13LFXeu3AEJJUyzwJ7nTd0/WXIEgnSp+jorWkuhgd9Wn9+cW+XC5HsWUtib23/FQOOm6rEWNv9tHsJTJDkBOI=
env:
  global:
  - SAUCE_USERNAME=snay
  - TRAVIS_NODE_VERSION="4.2"
matrix:
  include:
  - env: PLATFORM=ios-9.3
    os: osx
    osx_image: xcode7.3
    language: node_js
    node_js: '4.2'
  - env: PLATFORM=ios-10.0
    os: osx
    osx_image: xcode7.3
    language: node_js
    node_js: '4.2'
  - env: PLATFORM=ios-11.0
    os: osx
    osx_image: xcode8.3
    language: node_js
    node_js: '4.2'    
before_install:
- npm cache clean -f
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- node --version
- if [[ "$PLATFORM" =~ android ]]; then gradle --version; fi
- if [[ "$PLATFORM" =~ ios ]]; then npm install -g ios-deploy; fi
- if [[ "$PLATFORM" =~ android ]]; then echo y | android update sdk -u --filter android-22,android-23,android-24,android-25;
  fi
- git clone https://github.com/apache/cordova-paramedic /tmp/paramedic && pushd /tmp/paramedic
  && npm install && popd
- npm install -g cordova
install:
- npm install
script:
- npm test
- node /tmp/paramedic/main.js --config pr/$PLATFORM --plugin $(pwd) --shouldUseSauce
  --buildName travis-plugin-contacts-$TRAVIS_JOB_NUMBER

